-- UPA Database setup and seed script

-- Drop tables before setup

DROP TABLE categories CASCADE CONSTRAINTS;
DROP TABLE products CASCADE CONSTRAINTS;
DROP TABLE product_units CASCADE CONSTRAINTS;
DELETE FROM USER_SDO_GEOM_METADATA WHERE table_name = 'PRODUCTS' AND column_name = 'GEOMETRY';
DELETE FROM USER_SDO_GEOM_METADATA WHERE table_name = 'PRODUCT_UNITS' AND column_name = 'GEOMETRY';
DROP INDEX units_geometry_sidx;

-- Tables setup
-- Products and categories
CREATE TABLE categories (
    id INTEGER GENERATED by default on null as IDENTITY PRIMARY KEY,
    name VARCHAR(128),
    parent INTEGER NULL,
    CONSTRAINT FK_ParentCategory FOREIGN KEY (parent)
    REFERENCES Categories(id)
);

CREATE TABLE products (
    id INTEGER GENERATED by default on null as IDENTITY PRIMARY KEY,
    category_id INTEGER,
    name VARCHAR(128),
    price DECIMAL(8,4),
    image ORDSYS.ORDImage,
    image_si ORDSYS.SI_StillImage,
    image_ac ORDSYS.SI_AverageColor,
    image_ch ORDSYS.SI_ColorHistogram,
    image_pc ORDSYS.SI_PositionalColor,
    image_tx ORDSYS.SI_Texture,
    geometry SDO_GEOMETRY,
    geometry_meta_type VARCHAR(255),
    geometry_meta_radius binary_double NULL,
    geometry_meta_width binary_double NULL,
    geometry_meta_height binary_double NULL,
    CONSTRAINT FK_Category FOREIGN KEY (category_id)
    REFERENCES Categories(id)
);
INSERT INTO USER_SDO_GEOM_METADATA VALUES (
    'products', 'geometry',
    -- products geometry
    -- max size is that of the warehouse
    -- all products will start on [0,0]
    SDO_DIM_ARRAY(
        SDO_DIM_ELEMENT('X', 0, 100, 0.01),
        SDO_DIM_ELEMENT('Y', 0, 50, 0.01)
    ),
    NULL
);

CREATE TABLE product_units (
    id INTEGER GENERATED by default on null as IDENTITY PRIMARY KEY,
    product_id INTEGER,
    checked_in DATE,
    checked_out DATE NULL,
    geometry SDO_GEOMETRY,
    CONSTRAINT FK_Placement FOREIGN KEY (product_id)
    REFERENCES products(id)
);
INSERT INTO USER_SDO_GEOM_METADATA VALUES (
    'product_units', 'geometry',
    -- warehouse 100x50 metres
    SDO_DIM_ARRAY(
        SDO_DIM_ELEMENT('X', 0, 100, 0.01),
        SDO_DIM_ELEMENT('Y', 0, 50, 0.01)
    ),
    NULL
);
CREATE INDEX units_geometry_sidx ON product_units(geometry) INDEXTYPE IS MDSYS.SPATIAL_INDEX;

-- Seeding
INSERT INTO categories (name, parent) VALUES ('uno', NULL);
INSERT INTO categories (name, parent) VALUES ('dos', NULL);
INSERT INTO categories (name, parent) VALUES ('tres', NULL);
INSERT INTO categories (name, parent) VALUES ('quatro', NULL);

INSERT INTO products (category_id, name, price, image) VALUES ('1', 'SuperProduct', 42, ordsys.ordimage.init());
INSERT INTO products (category_id, name, price, image) VALUES ('2', 'MegaProduct', 69, ordsys.ordimage.init());
INSERT INTO products (category_id, name, price, image) VALUES ('3', 'UltraProduct', 9, ordsys.ordimage.init());

INSERT INTO product_units (product_id, checked_in, checked_out) VALUES ('1', TO_DATE('2019-12-16 13:17:27', 'YYYY-MM-DD HH24:MI:SS'), NULL);
